const CFG = window.BARBERFLOW_CONFIG || {};
const configured = CFG.SUPABASE_URL && CFG.SUPABASE_ANON_KEY && !CFG.SUPABASE_URL.includes("COLE_AQUI") && !CFG.SUPABASE_ANON_KEY.includes("COLE_AQUI");
const db = configured && window.supabase ? window.supabase.createClient(CFG.SUPABASE_URL, CFG.SUPABASE_ANON_KEY) : null;
const BARBERS = ["André", "Valmor", "Gustavo", "Leonardo"];
const SERVICES = [
  {name:"Degradê", price:45, duration:45}, {name:"Social", price:40, duration:45},
  {name:"Corte infantil", price:40, duration:45}, {name:"Freestyle / Desenho", price:5, duration:15},
  {name:"Sobrancelha", price:15, duration:15}, {name:"Barba simples", price:20, duration:30},
  {name:"Barboterapia", price:30, duration:30}, {name:"Corte máquina", price:30, duration:30}
];
let clients = [], appointments = [];
const $ = id => document.getElementById(id);
const money = n => Number(n || 0).toLocaleString("pt-BR", {style:"currency", currency:"BRL"});
function todayISO(){ const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
const esc = s => String(s ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function toast(msg,error=false){const el=$("toast");el.textContent=msg;el.className=error?"show error":"show";setTimeout(()=>el.className="",2800)}
function setConnection(ok,text){$("connectionDot").className=ok?"ok":"bad";$("connectionText").textContent=text}
function go(page){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("page-"+page).classList.add("active");const titles={dashboard:["Dashboard","Visão geral da barbearia"],agenda:["Agenda","Horários da barbearia"],agendamentos:["Agendamentos","Todos os horários cadastrados"],novo:["Novo agendamento","Cadastre o cliente e marque o horário"],clientes:["Clientes","Cadastro e histórico básico"],config:["Configuração","Banco online e backup"]};$("pageTitle").textContent=titles[page][0];$("pageSubtitle").textContent=titles[page][1];if(page==="dashboard")renderDashboard();if(page==="agenda")renderAgenda();if(page==="agendamentos")renderAppointments();if(page==="clientes")renderClients()}
document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.page)));
async function loadAll(){
  if(!db){setConnection(false,"Configure o Supabase");$("configStatus").innerHTML="<b>Não configurado.</b> Edite config.js com a URL e a chave pública.";return}
  try{const [c,a]=await Promise.all([db.from("clientes").select("*").order("nome"),db.from("agendamentos").select("*, clientes(nome,telefone)").order("data").order("horario")]);if(c.error)throw c.error;if(a.error)throw a.error;clients=c.data||[];appointments=a.data||[];setConnection(true,"Banco online conectado");$("configStatus").innerHTML="<b>Conectado.</b> O site está usando o Supabase.";fillClients();renderDashboard();renderAgenda();renderClients()}catch(e){console.error(e);setConnection(false,"Erro no banco");toast("Erro ao carregar o banco: "+e.message,true)}}
function fillClients(selected=""){const s=$("clientSelect");s.innerHTML='<option value="">Selecione um cliente...</option>'+clients.map(c=>`<option value="${c.id}">${esc(c.nome)}${c.telefone?" — "+esc(c.telefone):""}</option>`).join("");if(selected)s.value=selected}
function fillServices(){$("serviceSelect").innerHTML=SERVICES.map((s,i)=>`<label class="service-option"><input type="checkbox" name="serviceOption" value="${i}"><span>${esc(s.name)}</span><small>${money(s.price)} · ${s.duration} min</small></label>`).join("");document.querySelectorAll('input[name="serviceOption"]').forEach(x=>x.addEventListener("change",updateServicePreview));updateServicePreview()}
function selectedServices(){return [...document.querySelectorAll('input[name="serviceOption"]:checked')].map(x=>SERVICES[Number(x.value)])}
function updateServicePreview(){const selected=selectedServices();const price=selected.reduce((x,s)=>x+s.price,0),duration=selected.reduce((x,s)=>x+s.duration,0);$("servicePreview").innerHTML=selected.length?`<b>${selected.map(s=>esc(s.name)).join(" + ")}</b><span>${money(price)}</span><span>${duration} min</span>`:`<span>Selecione um ou mais serviços</span>`}
function overlaps(date,time,duration,barber,ignoreId=null){const start=new Date(`${date}T${time}:00`).getTime(),end=start+duration*60000;return appointments.some(a=>{if(a.id===ignoreId||a.data!==date||a.barbeiro!==barber||["cancelado","faltou"].includes(a.status))return false;const s=new Date(`${a.data}T${a.horario}:00`).getTime(),e=s+(Number(a.duracao)||0)*60000;return start<e&&end>s})}
$("appointmentForm").addEventListener("submit",async e=>{e.preventDefault();if(!db)return toast("Configure o Supabase primeiro.",true);const client_id=$("clientSelect").value,barber=$("barberSelect").value,date=$("appointmentDate").value,time=$("appointmentTime").value,selected=selectedServices();if(!client_id)return toast("Selecione ou cadastre um cliente.",true);if(!selected.length)return toast("Selecione pelo menos um serviço.",true);const serviceName=selected.map(s=>s.name).join(" + "),totalPrice=selected.reduce((x,s)=>x+s.price,0),totalDuration=selected.reduce((x,s)=>x+s.duration,0);if(!overlaps(date,time,totalDuration,barber)){}else return toast("Esse horário conflita com outro agendamento.",true);const {error}=await db.from("agendamentos").insert({cliente_id,barbeiro:barber,servico:serviceName,preco:totalPrice,duracao:totalDuration,data:date,horario:time,status:"agendado",observacoes:$( "appointmentNotes").value.trim()});if(error)return toast(error.message,true);toast("Agendamento criado!");e.target.reset();$("appointmentDate").value=todayISO();$("appointmentTime").value="09:00";fillServices();await loadAll();go("agenda")});
async function createClient(){const nome=$("clientName").value.trim(),telefone=$("clientPhone").value.trim(),observacoes=$("clientNotes").value.trim();if(!nome)return;if(!db)return toast("Configure o Supabase primeiro.",true);const {data,error}=await db.from("clientes").insert({nome,telefone,observacoes}).select("*").single();if(error)return toast(error.message,true);$("clientForm").reset();$("clientModal").classList.add("hidden");await loadAll();fillClients(data.id);toast("Cliente cadastrado e selecionado!")}
$("clientForm").addEventListener("submit",e=>{e.preventDefault();createClient()});function openClientModal(){$("clientModal").classList.remove("hidden");$("clientName").focus()}$("newClientBtn").onclick=openClientModal;$("newClientBtn2").onclick=openClientModal;$("closeClientModal").onclick=()=>$("clientModal").classList.add("hidden");$("clientModal").addEventListener("click",e=>{if(e.target.id==="clientModal")e.currentTarget.classList.add("hidden")});
function renderDashboard(){const t=todayISO(),today=appointments.filter(a=>a.data===t);$("statToday").textContent=today.length;$("statDone").textContent=today.filter(a=>a.status==="concluido").length;$("statRevenue").textContent=money(today.filter(a=>a.status==="concluido").reduce((x,a)=>x+Number(a.preco||0),0));$("statClients").textContent=clients.length;const upcoming=today.filter(a=>!["cancelado","faltou"].includes(a.status)).sort((a,b)=>a.horario.localeCompare(b.horario)).slice(0,8);$("dashboardList").innerHTML=upcoming.length?upcoming.map(card).join(""):"<div class=\"empty\">Nenhum agendamento para hoje.</div>"}
function card(a){return `<div class="appointment"><div><b>${esc(a.horario)}</b><span>${esc(a.clientes?.nome||"Cliente")}</span><small>${esc(a.servico)} · ${esc(a.barbeiro)}</small></div><span class="status ${a.status}">${esc(a.status)}</span></div>`}
function renderAgenda(){const date=$("agendaDate").value||todayISO(),barber=$("agendaBarber").value;let list=appointments.filter(a=>a.data===date&&(!barber||a.barbeiro===barber)).sort((a,b)=>a.horario.localeCompare(b.horario));const groups=barber?[barber]:BARBERS;$("agendaGrid").innerHTML=groups.map(b=>{const items=list.filter(a=>a.barbeiro===b);return `<div class="agenda-col"><h2>${b}</h2>${items.length?items.map(appointmentCard).join(""):"<div class=\"empty\">Livre</div>"}</div>`}).join("")}
function appointmentCard(a){return `<div class="agenda-item"><div class="time">${esc(a.horario)}</div><div class="appt-body"><b>${esc(a.clientes?.nome||"Cliente")}</b><span>${esc(a.servico)} · ${money(a.preco)}</span>${a.clientes?.telefone?`<small>${esc(a.clientes.telefone)}</small>`:""}<select onchange="changeStatus('${a.id}',this.value)"><option value="agendado" ${a.status==="agendado"?"selected":""}>Agendado</option><option value="concluido" ${a.status==="concluido"?"selected":""}>Concluído</option><option value="cancelado" ${a.status==="cancelado"?"selected":""}>Cancelado</option><option value="faltou" ${a.status==="faltou"?"selected":""}>Faltou</option></select></div></div>`}
window.changeStatus=async(id,status)=>{if(!db)return;const {error}=await db.from("agendamentos").update({status}).eq("id",id);if(error)return toast("Não foi possível atualizar o status: "+error.message,true);toast("Status atualizado e salvo no Supabase.");await loadAll()};
$("agendaDate").value=todayISO();$("agendaDate").addEventListener("change",renderAgenda);$("agendaBarber").addEventListener("change",renderAgenda);$("agendaToday").onclick=()=>{$("agendaDate").value=todayISO();renderAgenda()};
function renderClients(){const q=($("clientSearch").value||"").toLowerCase();const arr=clients.filter(c=>(c.nome+" "+(c.telefone||"")).toLowerCase().includes(q));$("clientsList").innerHTML=arr.length?arr.map(c=>{const count=appointments.filter(a=>a.cliente_id===c.id).length;return `<div class="client-row"><div><b>${esc(c.nome)}</b><span>${esc(c.telefone||"Sem telefone")}</span></div><small>${count} agendamento(s)</small></div>`}).join(""):"<div class=\"empty\">Nenhum cliente encontrado.</div>"}
$("clientSearch").addEventListener("input",renderClients);$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify({exportado_em:new Date().toISOString(),clientes,agendamentos:appointments},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="barberflow-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$("appointmentDate").value=todayISO();$("appointmentTime").value="09:00";fillServices();loadAll();

function renderAppointments(){
  const date=$("appointmentsDateFilter").value;
  const barber=$("appointmentsBarberFilter").value;
  const status=$("appointmentsStatusFilter").value;
  let list=appointments.filter(a=>(!date||a.data===date)&&(!barber||a.barbeiro===barber)&&(!status||a.status===status)).sort((a,b)=>(a.data+a.horario).localeCompare(b.data+b.horario));
  $("appointmentsList").innerHTML=list.length?list.map(a=>`<div class="appointment"><div><b>${esc(a.data.split("-").reverse().join("/"))} às ${esc(a.horario)}</b><span>${esc(a.clientes?.nome||"Cliente")} · ${esc(a.barbeiro)}</span><small>${esc(a.servico)} · ${money(a.preco)} · ${a.duracao} min</small>${a.clientes?.telefone?`<small>${esc(a.clientes.telefone)}</small>`:""}</div><div><select onchange="changeStatus('${a.id}',this.value)"><option value="agendado" ${a.status==="agendado"?"selected":""}>Agendado</option><option value="concluido" ${a.status==="concluido"?"selected":""}>Concluído</option><option value="cancelado" ${a.status==="cancelado"?"selected":""}>Cancelado</option><option value="faltou" ${a.status==="faltou"?"selected":""}>Faltou</option></select><button class="ghost" onclick="deleteAppointment('${a.id}')">Excluir</button></div></div>`).join(""):'<div class="empty">Nenhum agendamento encontrado.</div>';
}
window.deleteAppointment=async id=>{if(!db)return; if(!confirm("Excluir este agendamento?"))return; const {error}=await db.from("agendamentos").delete().eq("id",id); if(error)return toast(error.message,true); toast("Agendamento excluído."); await loadAll(); renderAppointments();};
["appointmentsDateFilter","appointmentsBarberFilter","appointmentsStatusFilter"].forEach(id=>$(id).addEventListener("change",renderAppointments));
$("appointmentsClearFilter").onclick=()=>{$("appointmentsDateFilter").value="";$("appointmentsBarberFilter").value="";$("appointmentsStatusFilter").value="";renderAppointments()};
